name: My Custom Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use the Common Workflow Template
        uses: ./.github/workflows/common-workflow.yml
