name: My Custom Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use the 2Common Workflow Template
        uses: ./.github/workflows/common-workflow.yml
